### ISSUE TITLE
Реализуйте рассылку welcome-писем

### ISSUE THREAD

**Issue by vctecc** [emiliskan/notifications_sprint_1#10]
Что нужно сделать:

    

- После регистрации пользователя в сервисе онлайн-кинотеатра отправлять приветственное письмо на указанный пользователем адрес электронной почты.

    - В письме должна быть ссылка для подтверждения адреса электронной почты.
   - Для удобной работы на мобильных устройствах сделайте ссылку в письме сокращённой.
    Сокращённая ссылка должна включать:
      -  уникальный идентификатор пользователя, чтобы считать визиты,
      - временну́ю метку, обозначающую период, до которого ссылка действительна, параметр redirectUrl, определяющий, куда перенаправить пользователя после успешного подтверждения адреса электронной почты.
  -  При переходе по просроченной ссылке должна открываться страница с ошибкой 404.
  -  При переходе по действительной ссылке в базе должен проставляться признак, что этот email подтверждён.
  -  После успешного подтверждения адреса электронной почты система перенаправляет пользователя по адресу redirectUrl.
    Конкретное значение параметра redirectUrl настраивается в панели админа. В ходе выполнения этого задания настройте редирект на главную страницу онлайн-кинотеатра.

**Comment by emiliskan** [comment]
хороший план, но нет
